# DB Config file
# MySQL

development:
  adapter: mysql
  database: heroku_dbf9e0680b7f87b
  username: b09192cfccb724
  password: 6d91032f
  host: us-cdbr-east-05.cleardb.net

test:
  adapter: mysql
  database: heroku_dbf9e0680b7f87b
  username: b09192cfccb724
  password: 6d91032f
  host: us-cdbr-east-05.cleardb.net

production:
  adapter: mysql
  database: heroku_dbf9e0680b7f87b
  username: b09192cfccb724
  password: 6d91032f
  host: us-cdbr-east-05.cleardb.net
